// <auto-generated />
namespace PantryManagementBudgetApp2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class pantryitemtaginventory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pantryitemtaginventory));
        
        string IMigrationMetadata.Id
        {
            get { return "202307211514237_pantryitem-tag-inventory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
